version: '3'
services:
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  nest-app:
    restart: on-failure
    build: .
    ports:
      - '81:3000'