version: '3'
services:
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    depends_on:
      - nest-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  nest-app:
    image: 'fonsecabarreto/nest-app'
    restart: on-failure
    ports:
      - '81:3000'