version: '3'
services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro