version: '3'
services:
  nginx: 
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - app
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx/certs"
  app:
    restart: on-failure
    image: fonsecabarreto/nest-app
    ports:
      - '3000:3000'
