version: '3'
services:
  nginx: 
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - app
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
  app:
    restart: on-failure
    image: fonsecabarreto/nest-app
    ports:
      - '3000:3000'
