
name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
env:
  IMAGE_NAME: nest-app
  REGISTRY_NAME: fonsecabarreto

jobs:
  pushToDockerHub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --target production --file Dockerfile --tag $REGISTRY_NAME/$IMAGE_NAME
      - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: docker push $REGISTRY_NAME/$IMAGE_NAME:latest
  deploy:
    needs: pushToDockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          PORT: 22
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME, REGISTRY_NAME,{{secrets.DOCKERHUB_PASSWORD}}, {{secrets.DOCKERHUB_USERNAME}}
          script: |
            echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
            docker stop $(echo $IMAGE_NAME)
            docker rm $(echo $IMAGE_NAME)
            docker pull $(echo $REGISTRY_NAME)/$(echo $IMAGE_NAME) &&
            docker run -d \
            --restart always \
            --name $(echo $IMAGE_NAME) \
            -p 3000:3000 \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME)