
name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
env:
  IMAGE_NAME: nest-app
  REGISTRY_NAME: fonsecabarreto

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          mkdir ../release-files
          cp  docker-compose-prod.yml ../release-files
          tar -cvf deploy.tar ../release-files/

      - name: copy file via ssh 
        uses: appleboy/scp-action@master
        with:
          PORT: 22
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          source: "docker-compose-prod.yml"
          target: "app"
          
