
name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
env:
  IMAGE_NAME: nest-app
  REGISTRY_NAME: fonsecabarreto

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
          
