
name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
env:
  IMAGE_NAME: nest-app
  REGISTRY_NAME: fonsecabarreto

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh 
        uses: appleboy/scp-action@master
        with:
          PORT: 22
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          source: "conf/nginx, conf/docker-compose.yml"
          target: "conf"
          rm: true
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          PORT: 22
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          script: | 
            echo "done"
            
          
