
name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - v*

env:
  IMAGE_NAME: nest-app
  REGISTRY_NAME: fonsecabarreto

jobs:

  pushToDockerHub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile --tag $REGISTRY_NAME/$IMAGE_NAME
      - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: docker push $REGISTRY_NAME/$IMAGE_NAME
  deploy:
    needs: pushToDockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copying docker-compose.yml to droplet
        uses: garygrossgarten/github-action-scp@release
        with:
          local: docker-compose-prod.yml
          remote: ~/
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          privateKey: ${{secrets.SSHKEY}}

